# Generated by Django 5.1.3 on 2024-11-30 19:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter the type of the equipment. (e.g., oven, tape measure etc.)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Enter period. (e.g.,years, months, weeks, days etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_sku', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='mfg_documents/% Y/% m/% d/')),
                ('approval_ref', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('by', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_manager.equipmentmanufacturer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_manager.equipmenttype')),
                ('calibration_period', models.ForeignKey(help_text='Calibration period.', on_delete=django.db.models.deletion.PROTECT, related_name='calibration', to='equipment_manager.period')),
                ('maintenance_period', models.ForeignKey(help_text='Maintenance period.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='equipment_manager.period')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=50)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('by', models.CharField(max_length=50)),
                ('eqp_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.equipmentmodel')),
            ],
            options={
                'ordering': ['internal_id'],
            },
        ),
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('record_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=400)),
                ('detail_date', models.DateField(default=datetime.date.today, help_text='Use this field to enter dates associated with the detail. (e.g., calibration due date, maintenance due date etc.)')),
                ('documents', models.FileField(upload_to='eqp_records/% Y/% m/% d/')),
                ('references', models.CharField(max_length=100)),
                ('entry_date', models.DateField(default=datetime.date.today, help_text='Use this field to record the date of this record.')),
                ('by', models.CharField(max_length=50)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.instance')),
                ('record_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.recorddetail')),
            ],
            options={
                'ordering': ['instance', 'entry_date'],
            },
        ),
        migrations.AddField(
            model_name='recorddetail',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_manager.recordtype'),
        ),
    ]
