# Generated by Django 5.1.3 on 2024-11-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0002_period_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='duration',
            field=models.IntegerField(help_text='Enter the integer value associated with the period.'),
        ),
    ]
