# Generated by Django 5.1.3 on 2024-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0003_alter_period_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='documents',
            field=models.FileField(upload_to='mfg_documents/'),
        ),
    ]
