# Generated by Django 5.1.3 on 2024-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0005_alter_recorddetail_options_alter_recordlog_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='duration',
            field=models.IntegerField(help_text='Enter the integer value associated with the period.', null=True),
        ),
    ]
