# Generated by Django 5.1.3 on 2024-11-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0006_alter_period_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='duration',
        ),
        migrations.AddField(
            model_name='period',
            name='rel_period',
            field=models.CharField(default=1, help_text='Use this field to enter the associated relativedelta value.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(help_text='Enter period in plain language. (e.g.,once per year, every 3 months, once per week etc.)', max_length=50),
        ),
    ]
