# Generated by Django 5.1.3 on 2024-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0007_remove_period_duration_period_rel_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='rel_period',
            field=models.CharField(help_text='Use this field to enter the associated relativedelta value.', max_length=20, null=True),
        ),
    ]
