# Generated by Django 5.1.3 on 2024-12-01 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0010_alter_recordlog_end_date_alter_recordlog_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='documents',
            field=models.FileField(blank=True, upload_to='mfg_documents/'),
        ),
        migrations.AlterField(
            model_name='recordlog',
            name='documents',
            field=models.FileField(blank=True, upload_to='eqp_records/'),
        ),
        migrations.AlterField(
            model_name='recordlog',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Use this end date  to enter dates associated with the detail. (e.g., test end date, maintenance due date etc.)'),
        ),
        migrations.AlterField(
            model_name='recordlog',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Use this start date to enter dates associated with the detail. (e.g., test start date, maintenance due date etc.)'),
        ),
    ]
