# Generated by Django 5.1.3 on 2024-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0016_alter_recordlog_end_date_alter_recordlog_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordlog',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='Use this field to enter the next date calibration or maintenance is due or end date of a range entry.', null=True, verbose_name='Due Date / End Date'),
        ),
        migrations.AlterField(
            model_name='recordlog',
            name='start_date',
            field=models.DateField(blank=True, default=None, help_text='Use this field to enter the date calibration or maintenance was performed or start date for a range entry.', null=True, verbose_name='Date Performed / Start Date'),
        ),
    ]
